export const SUPABASE_URL = 'https://csbcornmfvfgrylhvopx.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzYmNvcm5tZnZmZ3J5bGh2b3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDk5OTYsImV4cCI6MjA5MDYyNTk5Nn0.7VhFypFdX5D9D8OOwozWhoaeUArHRJe5PnqzQFXTcFc';
